name: Go CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: Install dependencies
        run: |
          go get -v -t -d ./...
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
      - name: Build code
        run: |
          go build -v ./...
      - name: Test code
        run: |
          go test -v -cover ./...
